[workspace]
authors = ["Tuatini Godard <email@tuatini.me>"]
channels = ["conda-forge"]
name = "isaacsim"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = { cmd = "./build.sh" }
run = {cmd = "bash -c 'if [ -f ./_build/linux-x86_64/release/isaac-sim.sh ]; then ./_build/linux-x86_64/release/isaac-sim.sh; else ./build.sh && ./_build/linux-x86_64/release/isaac-sim.sh; fi'"}

[dependencies]
gcc = "==11.4.0"
cxx-compiler = ">=1.5.2,<2"
