[workspace]
authors = ["Tuatini Godard <email@tuatini.me>"]
channels = ["conda-forge"]
name = "isaacsim"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = { cmd = "./build.sh" }
run = { cmd = "bash -c 'f=./_build/linux-x86_64/release/isaac-sim.sh; [ -f $f ] && $f || (./build.sh && $f)'"}
selector = { cmd = "bash -c 'f=./_build/linux-x86_64/release/isaac-sim.selector.sh; [ -f $f ] && $f || (./build.sh && $f)'"}
stream_server = { cmd = "bash -c 'f=./_build/linux-x86_64/release/isaac-sim.streaming.sh; [ -f $f ] && $f || (./build.sh && $f)'"}

[dependencies]
gcc = "==11.4.0"
cxx-compiler = ">=1.5.2,<2"
